/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      screens: {
        'xs': '375px',
        'sm': '480px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      },
      colors: {
        'mahotsav-purple': {
          50: '#f3e8ff',
          100: '#e9d5ff',
          200: '#ddd6fe',
          300: '#c4b5fd',
          400: '#a78bfa',
          500: '#8b5cf6',
          600: '#7c3aed',
          700: '#6d28d9',
          800: '#5b21b6',
          900: '#4c1d95',
          950: '#2e1065',
        },
        'mahotsav-gold': {
          50: '#fefce8',
          100: '#fef9c3',
          200: '#fef08a',
          300: '#fde047',
          400: '#facc15',
          500: '#eab308',
          600: '#ca8a04',
          700: '#a16207',
          800: '#854d0e',
          900: '#713f12',
          950: '#422006',
        },
        'mahotsav-pink': {
          50: '#fdf2f8',
          100: '#fce7f3',
          200: '#fbcfe8',
          300: '#f9a8d4',
          400: '#f472b6',
          500: '#ec4899',
          600: '#db2777',
          700: '#be185d',
          800: '#9d174d',
          900: '#831843',
          950: '#500724',
        },
      },
      animation: {
        'float': 'float 3s ease-in-out infinite',
        'pulse-slow': 'pulse 2s ease-in-out infinite',
        'marquee': 'marquee 30s linear infinite',
        'fadeInDown': 'fadeInDown 1s ease-out',
        'petalsRotate': 'petalsRotate 20s linear infinite',
        'sunRotate': 'sunRotate 20s linear infinite',
        'gentleFloat': 'gentleFloat 4s ease-in-out infinite',
        'slideUpBounce': 'slideUpBounce 0.5s ease-out forwards',
        'menuSlideRotate': 'menuSlideRotate 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
        'menuItemSlideIn': 'menuItemSlideIn 0.5s ease-out forwards',
        'spin-slow': 'spin 120s linear infinite',
        'spin-reverse': 'spin-reverse 10s linear infinite',
        'bounce-slow': 'bounce 2s infinite',
        'shine': 'shine 0.8s ease-in-out',
        'numberPulse': 'numberPulse 2s ease-in-out infinite',
        'modalSlideIn': 'modalSlideIn 0.3s ease',
        'fadeIn': 'fadeIn 0.3s ease-out',
        'dropdownSlideIn': 'dropdownSlideIn 0.3s ease-out',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        fadeInDown: {
          '0%': { opacity: '0', transform: 'translateY(-20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        petalsRotate: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(-360deg)' },
        },
        sunRotate: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        slideUpBounce: {
          '0%': { opacity: '0', transform: 'translateY(30px) scale(0.5)' },
          '60%': { opacity: '1', transform: 'translateY(-10px) scale(1.1)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        gentleFloat: {
          '0%, 100%': { transform: 'translateY(-50%) translateX(0px)' },
          '25%': { transform: 'translateY(-60%) translateX(5px)' },
          '50%': { transform: 'translateY(-40%) translateX(0px)' },
          '75%': { transform: 'translateY(-60%) translateX(-5px)' },
        },
        menuSlideRotate: {
          '0%': { transform: 'translateX(-100%) rotateY(-90deg)', opacity: '0' },
          '50%': { transform: 'translateX(-50%) rotateY(-45deg)', opacity: '0.5' },
          '100%': { transform: 'translateX(0) rotateY(0deg)', opacity: '1' },
        },
        menuItemSlideIn: {
          '0%': { opacity: '0', transform: 'translateX(-20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'spin-reverse': {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(-360deg)' },
        },
        shine: {
          '0%': { transform: 'translateX(-100%) rotate(-45deg)' },
          '100%': { transform: 'translateX(100%) rotate(-45deg)' },
        },
        numberPulse: {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.02)' },
        },
        modalSlideIn: {
          '0%': { opacity: '0', transform: 'translateY(-20px) scale(0.95)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        dropdownSlideIn: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}